title: "Jackal"
author: "jackal"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%d %B %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: Posts}
  - {file: "README.md", title: About}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Cara, icon: copyright, url: "https://cara.app/explore"}
  - {title: Github, icon: github, url: "https://github.com/hydraulic-mining-excavator"}
  - {title: Subscribe, icon: youtube, url: "https://www.youtube.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
